# Generated by Django 3.1.7 on 2022-11-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221115_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='behind_auth',
            field=models.BooleanField(default=False),
        ),
    ]
