# Generated by Django 3.2.13 on 2022-11-17 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_alter_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='like_users',
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(max_length=50),
        ),
        migrations.CreateModel(
            name='VoteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('like_moveis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('like_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
